### ISSUE TITLE
compile failed on almaLinux 9  

### ISSUE THREAD

**Issue by PsudoEyes** [stuartjamesmcnicholas/Moorhen#241]
As RHEL 9 removed bzr (Bazaar) package, when compiling with "./get_sources", error "./get_sources: line 7: bzr: command not found" occurred. 

** (RHEL 9 based Rocky Linux 9 may suffers from the same problem)**

This could be solved by install the breezy package as followed:

pip install breezy

then, change all bzr in the "get_sources" file into brz, save and run:

./get_sources

problem solved!

`./get_sources
Checking out libccp4
./get_sources: line 7: bzr: command not found

Checking out clipper
./get_sources: line 10: bzr: command not found

Checking out ssm
./get_sources: line 13: bzr: command not found

Checking out mmdb2
./get_sources: line 16: bzr: command not found

Checking out ccp4srs
./get_sources: line 19: bzr: command not found

Checking out rvapi
./get_sources: line 22: bzr: command not found

Checking out gesamt
./get_sources: line 25: bzr: command not found
`

**Comment by stuartjamesmcnicholas** [comment]
I am slightly surprised breezy did not install a bzr command as a link to brz. Anyway thanks!
